<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/druid.glb
-->

<script lang="ts">
  import {
    Color,
    Group,
    MeshToonMaterial,
    DataTexture,
    RedFormat,
  } from "three";

  import { OutlineEffect } from "three/addons/effects/OutlineEffect.js";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("/druid-web/static/models/druid.glb");

  const component = forwardEventHandlers();

  let alpha = 0.5;
  let beta = 0.5;
  let gamma = 0.5;
  const skinColor = new Color().setHex(0xdfb465);
  const fabricColor = new Color().setHex(0x79a48a);
  const hairColor = new Color().setHex(0xffffff);
  const inkColor = new Color().setHex(0x000000);

  const colors = new Uint8Array(10);
  const gradMap = new DataTexture(colors, colors.length, 1, RedFormat);

  let nose: THREE.Mesh;
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.NurbsPath.geometry}>
      <T.MeshToonMaterial color={fabricColor} />
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.Head.geometry}>
      <T.MeshToonMaterial color={skinColor} />
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.Eye.geometry}>
      <T.MeshToonMaterial color={inkColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Nose.geometry}
      material={gltf.materials.Skin}
      bind:ref={nose}
    >
      <T.MeshToonMaterial color={skinColor} />
    </T.Mesh>
    <T.Mesh geometry={gltf.nodes.Eyebrow.geometry}>
      <T.MeshToonMaterial color={inkColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Skin}
      position={[-0.02, -0.1, 0]}
    >
      <T.MeshToonMaterial color={skinColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Torus001.geometry}
      material={gltf.materials.Fabric}
      position={[0, 2.45, -0.02]}
      rotation={[-0.11, 0, 0]}
      scale={[1, 1, 0.91]}
    >
      <T.MeshToonMaterial color={fabricColor} gradientMap={gradMap} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere009.geometry}
      material={gltf.materials.Hair}
      position={[0.77, 2.25, 0.05]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere001.geometry}
      material={gltf.materials.Hair}
      position={[0.76, 2.22, -0.13]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere002.geometry}
      material={gltf.materials.Hair}
      position={[0.77, 2.05, -0.27]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.2}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere003.geometry}
      material={gltf.materials.Hair}
      position={[0.77, 2.15, 0.14]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere004.geometry}
      material={gltf.materials.Hair}
      position={[0.82, 2.31, -0.06]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere005.geometry}
      material={gltf.materials.Hair}
      position={[0.81, 1.76, -0.21]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.2}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere006.geometry}
      material={gltf.materials.Hair}
      position={[0.8, 1.91, -0.27]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.2}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere007.geometry}
      material={gltf.materials.Hair}
      position={[0.71, 2.23, -0.29]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere008.geometry}
      material={gltf.materials.Hair}
      position={[0.68, 2.07, -0.39]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere010.geometry}
      material={gltf.materials.Hair}
      position={[0.72, 1.89, -0.37]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Icosphere011.geometry}
      material={gltf.materials.Hair}
      position={[0.83, 1.6, -0.1]}
      rotation={[-0.19, -0.06, -0.03]}
      scale={0.15}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      name="Beard"
      geometry={gltf.nodes.Beard.geometry}
      material={gltf.materials.Hair}
      morphTargetDictionary={gltf.nodes.Beard.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.Beard.morphTargetInfluences}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T.Mesh
      name="Mustache"
      geometry={gltf.nodes.Mustache.geometry}
      material={gltf.materials.Hair}
      morphTargetDictionary={gltf.nodes.Mustache.morphTargetDictionary}
      morphTargetInfluences={gltf.nodes.Mustache.morphTargetInfluences}
    >
      <T.MeshToonMaterial color={hairColor} />
    </T.Mesh>
    <T is={gltf.nodes.spine} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
