<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/druid.glb -o src/lib/models/druid.svelte
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();

  const gltf = useGltf("/druid-web/models/druid.glb");

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.NurbsPath.geometry}
      material={gltf.materials.Fabric}
    />
    <T.Mesh
      geometry={gltf.nodes.Head.geometry}
      material={gltf.materials.Skin}
    />
    <T.Mesh geometry={gltf.nodes.Eye.geometry} material={gltf.materials.Ink} />
    <T.Mesh
      geometry={gltf.nodes.Nose.geometry}
      material={gltf.materials.Skin}
    />
    <T.Mesh
      geometry={gltf.nodes.Eyebrow.geometry}
      material={gltf.materials.Ink}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Skin}
    />
    <T.Mesh
      geometry={gltf.nodes.Torus001.geometry}
      material={gltf.materials.Fabric}
      position={[0, 2.45, -0.02]}
      rotation={[-0.11, 0, 0]}
      scale={[1, 1, 0.91]}
    />
    <T.Mesh
      geometry={gltf.nodes.Beard.geometry}
      material={gltf.materials.Hair}
    />
    <T.Mesh
      geometry={gltf.nodes.Mustache.geometry}
      material={gltf.materials.Hair}
    />
    <T is={gltf.nodes.spine} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
